// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using QDCeValutazioni.DA;
using System;

namespace QDCeValutazioni.DA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191209185323_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("QDCeValutazioni.DA.Models.Assegnazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Codice");

                    b.Property<string>("Motivazione");

                    b.Property<int?>("QdcId");

                    b.Property<int?>("RequisitoId");

                    b.Property<int?>("Voto");

                    b.HasKey("Id");

                    b.HasIndex("QdcId");

                    b.HasIndex("RequisitoId");

                    b.ToTable("Assegnazioni");
                });

            modelBuilder.Entity("QDCeValutazioni.DA.Models.Qdc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CognomeFormatore");

                    b.Property<string>("CognomePerito1");

                    b.Property<string>("CognomePerito2");

                    b.Property<DateTime?>("DataConsegna");

                    b.Property<DateTime?>("DataInizio");

                    b.Property<string>("Descrizione");

                    b.Property<string>("MailFormatore");

                    b.Property<string>("MailPerito1");

                    b.Property<string>("MailPerito2");

                    b.Property<string>("NomeFormatore");

                    b.Property<string>("NomePerito1");

                    b.Property<string>("NomePerito2");

                    b.Property<int?>("NumeroOre");

                    b.Property<DateTime?>("OraFine");

                    b.Property<DateTime?>("OraInizio");

                    b.Property<string>("PathSave");

                    b.Property<string>("PathTemplate");

                    b.Property<string>("Titolo");

                    b.HasKey("Id");

                    b.ToTable("Qdcs");
                });

            modelBuilder.Entity("QDCeValutazioni.DA.Models.Requisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodiceReq");

                    b.Property<string>("Descrizione");

                    b.Property<string>("Titolo");

                    b.HasKey("Id");

                    b.ToTable("Requisiti");
                });

            modelBuilder.Entity("QDCeValutazioni.DA.Models.Assegnazione", b =>
                {
                    b.HasOne("QDCeValutazioni.DA.Models.Qdc", "Qdc")
                        .WithMany()
                        .HasForeignKey("QdcId");

                    b.HasOne("QDCeValutazioni.DA.Models.Requisito", "Requisito")
                        .WithMany()
                        .HasForeignKey("RequisitoId");
                });
#pragma warning restore 612, 618
        }
    }
}
